### ISSUE TITLE
Handle undefined value for location

### ISSUE THREAD

**Issue by khoadng** [axelav/logseq-plugin-weather#1]
At my current location, the plugin will print two values for locations as below:

`[[undefined]]`
`[[{city name}]]`

The undefined values will create unwanted pages so I want to filter them.
It should be easy enough so I would like to work on this issue. 
However I don't know where to start, since I can't change the code directly on my app.

**Comment by axelav** [comment]
I've bullt an API endpoint to fetch the weather forecast and location data, so I think I'll need to fix this in that API. The plugin should work properly after that. Will update this issue once I have made that fix.

**Comment by axelav** [comment]
@khoadng I've updated the API to better handle `undefined` locations. Please let me know if this resolves your issue.

**Comment by axelav** [comment]
I've also updated the plugin with a new setting to exclude the location field if you'd like. Please update to version `0.2.0` if you'd like to try that option.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/59404/212561858-0b7b4eed-17e0-42df-b10f-990b6775bfe9.png">

**Comment by khoadng** [comment]
It is working now. Thanks for your support.
