### ISSUE TITLE
Add options to use ℃ & format the input

### ISSUE THREAD

**Issue by karkraeg** [axelav/logseq-plugin-weather#2]
Hi, would it be possible to gain control over how the temperature is displayed and how this is inserted via settings?

https://github.com/axelav/logseq-plugin-weather/blob/002c6d97f1026fe5ef1ea4e0d201e438156068f0/src/index.ts#L124

Thanks!

**Comment by temperatio** [comment]
It would be great.

**Comment by karkraeg** [comment]
The API used only returns Farenheit: https://weather-api.honkytonkin.workers.dev/?lat=40.6892684994514&lon=-74.04448753420193

So it would be necessary to convert this. I guess I could fork this repo but I don't know how to implement a setting menu in Logseq to change this setting.

**Comment by axelav** [comment]
Yes, I'm using a custom API to return the weather forecast & location data. I can update that API to allow for celsius and add an option in the logseq plugin settings.

Re the formatting, what do you have in mind?

**Comment by axelav** [comment]
@karkraeg @temperatio I've added a new setting for metric or imperial units for the plugin. Please upgrade to version `0.3.0` of the plugin to enable it. Let me know if this works better for you. 

<img width="479" alt="image" src="https://user-images.githubusercontent.com/59404/212563235-875a78c1-528a-4191-ae52-a715cc5d53b1.png">

<img width="226" alt="image" src="https://user-images.githubusercontent.com/59404/212563255-b3473898-132d-4252-9de5-6b7f4802af65.png">

**Comment by karkraeg** [comment]
Thanks for metric units!

> Re the formatting, what do you have in mind?

Be able to disable sun, moon, wind and humidity Information in the settings.json

**Comment by axelav** [comment]
> Be able to disable sun, moon, wind and humidity Information in the settings.json

That's a great idea. I'll take care of that, hopefully today, and let you know when it's ready.

**Comment by axelav** [comment]
@karkraeg version `0.4.0` was just published with these options available in the plugin settings. Thanks again for your feedback!

**Comment by karkraeg** [comment]
Works fine! Thanks 😄

**Comment by temperatio** [comment]
Works well for me too!

Thanks a lot
