### ISSUE TITLE
Option to use slash-command or other syntax to use in a template?

### ISSUE THREAD

**Issue by karkraeg** [axelav/logseq-plugin-weather#3]
Hi, it's me again ;) Right now one can only use the right-click method - would it be possible to use something like `{{renderer weather}}` so the weather would be inserted when calling a template?

**Comment by axelav** [comment]
Hi again @karkraeg :) I've thought about adding that functionality as well. I'll have to look into it some though. Definitely seems possible.

**Comment by axelav** [comment]
@karkraeg pushed a new version `v0.5.0` with a new slash command to "Add current weather data" in the current block.

https://github.com/axelav/logseq-plugin-weather/releases/tag/v0.5.0

**Comment by karkraeg** [comment]
nice, works like a charm!

**Comment by jorlando-tuik** [comment]
Hello @karkraeg  and @axelav . I try to make this work in a template with the following.

```
{{renderer :"Add current weather data"}}
```

But this never triggers when I run the template. Any chance you can post the syntax that works?

**Comment by axelav** [comment]
@jorlando-tuik this plugin isn't built to work like that. You'll need to use logseq's slash commands by typing a `/` in a block and searching for "Add current weather data" or by right clicking on on a block's bullet and selecting "Add current weather data".

**Comment by JamieOrlando-Engooden** [comment]
Thank you @axelav

**Comment by jorlando-tuik** [comment]
@axelav  @karkraeg  Thank you very much for getting back to me. I was able to implement this myself. I submitted https://github.com/axelav/logseq-plugin-weather/pull/7 over to you with the feature if you are interested.

Either way, thanks for putting the plugin together. It is great stuff.

**Comment by axelav** [comment]
Thanks @jorlando-tuik - I'm traveling for a few days but will take a look at your PR when I am back earlier next week.
