### ISSUE TITLE
Feature Request: Weather for any Places

### ISSUE THREAD

**Issue by thebigalwisi** [axelav/logseq-plugin-weather#6]
Hi
is there a possibility not to fix the place in the settings but to pass it with the query, so that you can query any places?

**Comment by axelav** [comment]
This already exists. Enter the coordinates in a block, then use the slash command or context menu to get weather for any location. 

https://github.com/axelav/logseq-plugin-weather?tab=readme-ov-file#add-current-weather-data-for-a-specific-location
